name: Publish to PyPI

on:
    push:
        branches:
            - main
        tags:
            - "v*"

jobs:
    check:
        uses: ./.github/workflows/check.yml

    wheel:
        runs-on: ubuntu-latest
        needs: [check]

        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
                persist-credentials: false

            - name: Install the latest version of uv
              uses: astral-sh/setup-uv@v3
              with:
                enable-cache: true
                cache-dependency-glob: "pyproject.toml"
                github-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Build wheel
              run: uv build

            - uses: actions/upload-artifact@v4
              with:
                name: wheel
                path: dist/

    test-publish:
        runs-on: ubuntu-latest
        needs: [wheel]
        environment:
            name: testpypi
            url: https://test.pypi.org/p/git-check-ignore
        permissions:
            id-token: write
        steps:
            - uses: actions/download-artifact@v4

            - name: Publish package distributions to TestPyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                repository-url: https://test.pypi.org/legacy/

    publish:
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        needs: [wheel]
        environment:
            name: pypi
            url: https://pypi.org/p/git-check-ignore
        permissions:
            id-token: write
        steps:
            - uses: actions/download-artifact@v4

            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
